baseURL = "https://www.hexen.haus/"
title = "Unser kleines Hexenhaus"
languageCode = "de-DE"
DefaultContentLanguage = "de"
enableemoji = true

[languages]
  [languages.de]
    weight = 1
    languageName = "Deutsch"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[module]

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/js/alpinejs"

  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/lazysizes"

[markup.goldmark.renderer]
unsafe = true

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
