name: GitHub Pages

on:
  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # with:
      #   submodules: true

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-${{ hashFiles('package-lock.json') }}
          npm-

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.76.5'
        # extended: true

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    - name: Install Tools
      run: npm install -g postcss-cli autoprefixer

    - name: NPM install
      run: npm install

    - name: Build
      run: hugo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: main
        # cname: hexen.haus
